version: "3.8"
services:
  db:
    image: postgres:16
    container_name: portfolio-postgres-db
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: hatachoru
      POSTGRES_PASSWORD: Youmeisyu9908
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
